DATABASE:
  URL: '192.168.1.17'
  PORT: '3306'
  USER: 'root'
  PASSWORD: 'GMND'
  DATABASE: 'GMND'
OPC-UA:
  - NAME: PLC_Demo_0
    URL: '192.168.1.17'
    PORT: '4840'
    USER: ''
  - NAME: PLC_Demo_1
    URL: '192.168.1.17'
    PORT: '4840'
    USER: ''