version: '3'

services:
  grafana-service:
    build:
      context: ./containers-confs/files/grafana/
      dockerfile: Dockerfile
      args:
        - VERSION=${GRAFANA_VERSION}
        - INFLUXDB_DATASOURCE_USER=${INFLUXDB_ADMIN_USER}
        - INFLUXDB_DATASOURCE_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./containers-datas/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
  influxdb-service:
      image: influxdb:${INFLUXDB_VERSION}
      volumes:
        - ./containers-datas/influxdb/data:/var/lib/influxdb
      environment:
        - INFLUXDB_DB=db_metrics
        - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_HTTP_AUTH_ENABLED=true
        - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      restart: unless-stopped
  # node-red-service:
  #   build:
  #     context: ./containers-confs/files/node-red/
  #     dockerfile: Dockerfile
  #     args:
  #       - VERSION=${NODERED_VERSION}
  #   volumes:
  #     - ./containers-datas/node-red/config:/data
  #   environment:
  #     - NODERED_ADMIN_USER=${NODERED_ADMIN_USER}
  #     - NODERED_ADMIN_PASSWORD_HASH=${NODERED_ADMIN_PASSWORD_HASH}
  #   ports:
  #     - 1880:1880
  #   restart: unless-stopped
  telegraf-service:
    build:
      context: ./containers-confs/files/telegraf/
      dockerfile: Dockerfile
      args:
        - VERSION=${TELEGRAF_VERSION}
        - INFLUXDB_OUTPUT_USER=${INFLUXDB_ADMIN_USER}
        - INFLUXDB_OUTPUT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
    restart: unless-stopped
    environment :
      - HOST_PROC=/host/proc
  mqtt-service:
    image: eclipse-mosquitto:${MOSQUITTO_VERSION}
    ports:
      - "1883:1883"
    restart: unless-stopped
  portainer-service:
    image: portainer/portainer:${PORTAINER_VERSION}
    volumes:
      - ./containers-datas/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: unless-stopped
