version: '3'

services:
  python-service:
    build:
      context: .
      dockerfile: dockerfile-python
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/usr/lib/python3.8/site-packages
    command: python ./main.py

  mariadb-service:
    image: linuxserver/mariadb:arm32v7-110.4.12mariabionic-ls57
    environment:
      - MYSQL_ROOT_PASSWORD=GMND
      - MYSQL_DATABASE=GMND
      - MYSQL_USER=root
      - MYSQL_PASSWORD=GMND
    volumes:
      - v_mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  grafana-service:
    build:
      context: .
      dockerfile: dockerfile-grafana
      args:
        - GRAFANA_VERSION=6.7.2
    volumes:
      - v_grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  portainer-service:
    image: portainer/portainer
    volumes:
      - v_portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: unless-stopped

volumes:
  v_mariadb:
  v_grafana:
  v_portainer: